/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as AuctionAuctionIdRouteImport } from './routes/auction.$auctionId'
import { Route as LiveLiveIdRouteImport } from './routes/live.$liveId'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as ProdutoProductIdRouteImport } from './routes/produto.$productId'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as VendedorStoreIdRouteImport } from './routes/vendedor.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdRoute = AuctionAuctionIdRouteImport.update({
  id: '/auction/$auctionId',
  path: '/auction/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLiveIdRoute = LiveLiveIdRouteImport.update({
  id: '/live/$liveId',
  path: '/live/$liveId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoProductIdRoute = ProdutoProductIdRouteImport.update({
  id: '/produto/$productId',
  path: '/produto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const VendedorStoreIdRoute = VendedorStoreIdRouteImport.update({
  id: '/vendedor/$storeId',
  path: '/vendedor/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auctions': typeof AuctionsRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/criar': typeof CriarRoute
  '/explorar': typeof ExplorarRoute
  '/loja': typeof LojaRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/seller': typeof SellerRouteWithChildren
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/vendedor/$storeId': typeof VendedorStoreIdRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auctions': typeof AuctionsRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/criar': typeof CriarRoute
  '/explorar': typeof ExplorarRoute
  '/loja': typeof LojaRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/vendedor/$storeId': typeof VendedorStoreIdRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/auctions': typeof AuctionsRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/criar': typeof CriarRoute
  '/explorar': typeof ExplorarRoute
  '/loja': typeof LojaRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/seller': typeof SellerRouteWithChildren
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$productId': typeof ProdutoProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/vendedor/$storeId': typeof VendedorStoreIdRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ao-vivo'
    | '/auctions'
    | '/carrinho'
    | '/checkout'
    | '/criar'
    | '/explorar'
    | '/loja'
    | '/pedidos'
    | '/perfil'
    | '/seller'
    | '/auction/$auctionId'
    | '/live/$liveId'
    | '/pedido/$orderId'
    | '/produto/$productId'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/vendedor/$storeId'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ao-vivo'
    | '/auctions'
    | '/carrinho'
    | '/checkout'
    | '/criar'
    | '/explorar'
    | '/loja'
    | '/pedidos'
    | '/perfil'
    | '/auction/$auctionId'
    | '/live/$liveId'
    | '/pedido/$orderId'
    | '/produto/$productId'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/vendedor/$storeId'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/ao-vivo'
    | '/auctions'
    | '/carrinho'
    | '/checkout'
    | '/criar'
    | '/explorar'
    | '/loja'
    | '/pedidos'
    | '/perfil'
    | '/seller'
    | '/auction/$auctionId'
    | '/live/$liveId'
    | '/pedido/$orderId'
    | '/produto/$productId'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/vendedor/$storeId'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AoVivoRoute: typeof AoVivoRoute
  AuctionsRoute: typeof AuctionsRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  CriarRoute: typeof CriarRoute
  ExplorarRoute: typeof ExplorarRoute
  LojaRoute: typeof LojaRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  SellerRoute: typeof SellerRouteWithChildren
  AuctionAuctionIdRoute: typeof AuctionAuctionIdRoute
  LiveLiveIdRoute: typeof LiveLiveIdRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  ProdutoProductIdRoute: typeof ProdutoProductIdRoute
  VendedorStoreIdRoute: typeof VendedorStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId': {
      id: '/auction/$auctionId'
      path: '/auction/$auctionId'
      fullPath: '/auction/$auctionId'
      preLoaderRoute: typeof AuctionAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$liveId': {
      id: '/live/$liveId'
      path: '/live/$liveId'
      fullPath: '/live/$liveId'
      preLoaderRoute: typeof LiveLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$productId': {
      id: '/produto/$productId'
      path: '/produto/$productId'
      fullPath: '/produto/$productId'
      preLoaderRoute: typeof ProdutoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/vendedor/$storeId': {
      id: '/vendedor/$storeId'
      path: '/vendedor/$storeId'
      fullPath: '/vendedor/$storeId'
      preLoaderRoute: typeof VendedorStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SellerRouteChildren {
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerDashboardRoute: SellerDashboardRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AoVivoRoute: AoVivoRoute,
  AuctionsRoute: AuctionsRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  CriarRoute: CriarRoute,
  ExplorarRoute: ExplorarRoute,
  LojaRoute: LojaRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  SellerRoute: SellerRouteWithChildren,
  AuctionAuctionIdRoute: AuctionAuctionIdRoute,
  LiveLiveIdRoute: LiveLiveIdRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  ProdutoProductIdRoute: ProdutoProductIdRoute,
  VendedorStoreIdRoute: VendedorStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
